% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name hello_world
%  @associatedFile /MATLAB Drive/hello_world.m
%  @mostRecentlyActioned true
%  @uniqueId 5DCB1517

hello_world

%% @name Student
%  @associatedFile /MATLAB Drive/Student.m
%  @mostRecentlyActioned true
%  @uniqueId F0C2A13F

Student

%% @name fibonacci_till_n
%  @associatedFile /MATLAB Drive/Basic_Learning/Fibonacci/fibonacci_till_n.m
%  @mostRecentlyActioned true
%  @uniqueId FB02EEAE

fibonacci_till_n

%% @name cs_123_narcisstic_numbers
%  @associatedFile /MATLAB Drive/Published/cs_123_narcisstic_numbers.m
%  @mostRecentlyActioned true
%  @uniqueId 5FF2B72F

cs_123_narcisstic_numbers

%% @name cs_123_q1
%  @associatedFile /MATLAB Drive/cs_123_q1.m
%  @mostRecentlyActioned true
%  @uniqueId 7BA4C631

cs_123_q1

%% @name cs123_key_generation
%  @associatedFile /MATLAB Drive/cs123_lab_4/cs123_key_generation.m
%  @mostRecentlyActioned true
%  @uniqueId 37E23DE9

cs123_key_generation

%% @name cs123_gen_d
%  @associatedFile /MATLAB Drive/cs123_lab_5/cs123_gen_d.m
%  @mostRecentlyActioned true
%  @uniqueId D985950A

cs123_gen_d

%% @name cs123_midsem
%  @associatedFile /MATLAB Drive/cs123_midsem.m
%  @mostRecentlyActioned true
%  @uniqueId 03528086

cs123_midsem

